### ISSUE TITLE
Can't run gz sim (Possibly after some updates)

### ISSUE THREAD

**Issue by mini-1235** [gazebosim/gz-sim#3024]
## Environment
* OS Version: 24.04
* Source or binary build?
```
ros-rolling-ros-gz-bridge/noble,now 3.0.3-1noble.20250730.164501 amd64 [installed,automatic]
ros-rolling-ros-gz-image/noble,now 3.0.3-1noble.20250730.170500 amd64 [installed,automatic]
ros-rolling-ros-gz-interfaces/noble,now 3.0.3-1noble.20250730.143335 amd64 [installed,automatic]
ros-rolling-ros-gz-sim-demos/noble,now 3.0.3-1noble.20250730.181000 amd64 [installed,automatic]
ros-rolling-ros-gz-sim/noble,now 3.0.3-1noble.20250730.163723 amd64 [installed,automatic]
ros-rolling-ros-gz/noble,now 3.0.3-1noble.20250730.181601 amd64 [installed]
```
* If this is a GUI or sensor rendering bug, describe your GPU and rendering system. Otherwise delete this section. 
    - Rendering plugin: [ogre | ogre2]. 
      - [ ] Sensor rendering error. 
      - [ ] GUI rendering error. 
    - EGL headless mode:
      - [ ] Running in EGL headless mode 
    - Generally, mention all circumstances that might affect rendering capabilities: 
      - [ ] running on a dual GPU machine (integrated GPU + discrete GPU)
      - [ ] running on a multi-GPU machine (it has multiple discrete GPUs)
      - [ ] running on real hardware
      - [ ] running in virtual machine
      - [ ] running in Docker/Singularity
      - [ ] running remotely (e.g. via SSH)
      - [ ] running in a cloud
      - [ ] using VirtualGL, XVFB, Xdummy, XVNC or other indirect rendering utilities
      - [ ] GPU is concurrently used for other tasks
        - [ ] desktop acceleration
        - [ ] video decoding (i.e. a playing Youtube video)
        - [ ] video encoding
        - [ ] CUDA/ROCm computations (Tensorflow, Torch, Caffe running)
        - [ ] multiple simulators running at the same time
      - [ ] other...
    - Rendering system info:
      - On Linux, provide the outputs of the following commands:
          ```bash
          LANG=C lspci -nn | grep VGA  # might require installing pciutils
          echo "$DISPLAY"
          LANG=C glxinfo -B | grep -i '\(direct rendering\|opengl\|profile\)'  # might require installing mesa-utils package
          ps aux | grep Xorg
          sudo env LANG=C X -version  # if you don't have root access, try to tell the version of Xorg e.g. via package manager
          ```
      - On Windows, run `dxdiag` and report the GPU-related information.
      - On Mac OS, open a terminal and type `system_profiler SPDisplaysDataType`. Copy the output here.
        

      ```
      version number:    11.0
      X.Org version: 21.1.11
      ```

- [ ] Please, attach the ogre.log or ogre2.log file from  `~/.gz/rendering` 

<details>

```
MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
```

</details>

## Description
* Expected behavior: 
Gazebo working properly

* Actual behavior: 
On my rolling docker container, after I do a `sudo apt upgrade`, it seems that gazebo cannot render anything, and shows the error above. Before I do the upgrade command (10 Aug), everything is working properly. 

I tried to pull the latest rolling images, same thing happens. But I can run gazebo properly outside the container (Jazzy / Harmonic)

## Steps to reproduce

1.  pull nav2 rolling nightly image
```
docker pull ghcr.io/ros-navigation/nav2_docker:rolling-nightly
```
2. run gazebo
```
gz sim
```

## Output

Stuck in this page
<img width="824" height="703" alt="Image" src="https://github.com/user-attachments/assets/0025c2d6-d94f-4653-8596-ee5994da6cd9" />

**Comment by arjo129** [comment]
Any chance you could run it with `-v 4` so we have a more complete output.

**Comment by mini-1235** [comment]
> Any chance you could run it with `-v 4` so we have a more complete output.

Sure, I pasted it here https://pastebin.com/nk013T0y

**Comment by darmsDD** [comment]
OS: Ubuntu 24.04.2 LTS

I have the same problem. I can run gazebo fine outside of docker, but inside it gives me an error:
_libEGL warning: egl: failed to create dri2 screen
MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)_

I started gazebo with the command _gz sim --verbose 4_ and then chose a simulation. I tried a couple of simulations but all of them give the same error.

The complete log can be found at : https://pastebin.com/PiqQEMb7

**Comment by arjo129** [comment]
Thanks can you tell me what Graphics card/arguments you passed to docker? Are you using any Nvidia GPU/what version of docker are you using? Have you passed in th the gpus to your container via `--gpus-all`? This error often arises when the graphics drivers are not correctly loaded in a container.

**Comment by mini-1235** [comment]
> Thanks can you tell me what Graphics card/arguments you passed to docker? Are you using any Nvidia GPU/what version of docker are you using? Have you passed in th the gpus to your container via `--gpus-all`? This error often arises when the graphics drivers are not correctly loaded in a container.

For me, it's 
```
docker run --gpus all -it --ipc=host --net=host --privileged -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -e NVIDIA_DRIVER_CAPABILITIES=all ghcr.io/ros-navigation/nav2_docker:rolling-nightly
```

```
> docker --version
Docker version 27.4.1, build b9d17ea
```

```
> nvidia-smi

Fri Aug 15 23:17:31 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.163.01             Driver Version: 550.163.01     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   41C    P3            749W /   35W |       8MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      5592      G   /usr/lib/xorg/Xorg                              4MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by darmsDD** [comment]
Docker version 28.3.3, build 980b856

I am using docker compose to generate my container and the vscode extension to build and run it.

<img width="983" height="198" alt="Image" src="https://github.com/user-attachments/assets/a0dce6f8-a1fe-4d16-9978-0bad881eaef8" />

<img width="612" height="63" alt="Image" src="https://github.com/user-attachments/assets/6e5498b4-f9d1-422c-af1f-1ee320eb0876" />




About the GPU, at https://docs.docker.com/compose/how-tos/gpu-support/ it says to add
```
deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

```

to you docker compose yaml file. After I did this, I could check my gpu inside the docker using the command
``` nvidia-smi ```.

```
Fri Aug 15 19:17:13 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.163.01             Driver Version: 550.163.01     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060        Off |   00000000:01:00.0  On |                  N/A |
|  0%   50C    P8             19W /  170W |     786MiB /  12288MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+
```

To verify if I had access, I opened another terminal (still inside the container) and ran the program glxgears.

```
sudo apt install -y mesa-utils
glxgears
```
And then, ran again ``` nvidia-smi ```.

```
Fri Aug 15 19:26:15 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.163.01             Driver Version: 550.163.01     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060        Off |   00000000:01:00.0  On |                  N/A |
|  0%   50C    P5             20W /  170W |     781MiB /  12288MiB |     41%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     11309      G   glxgears                                       77MiB |
+-----------------------------------------------------------------------------------------+
```


But the problem with gazebo still persisted.
I am not sure if these are the equivalent of --gpu-all.
If you have any suggestions, I am all ears.
I can post the docker compose file here later.

**Comment by arilow** [comment]
Hi! I'm having the same problem. Using a Docker container with Ubuntu 24 and Gazebo harmonic

**Comment by MDEAGEWT** [comment]
I’m seeing the same issue. Adding `--runtime=nvidia` to the Docker startup script fixes it for me.

**Comment by arjo129** [comment]
@darmsDD if what @MDEAGEWT says is true then we need to add the following to your docker-compose configuration: https://github.com/docker/compose/issues/12203#issuecomment-2410467686

@mini-1235 you probably just need to append `--runtime=nvidia`.

If this solves the issue for you then let me know.

**Comment by arilow** [comment]
It worked for me. Thanks!

**Comment by darmsDD** [comment]
First of all, thank you for the tip of using runtime @MDEAGEWT and @arjo129. I just had to add some flags for it to properly work.  
I also decided to test multiple configurations to see what works.
I tested some configurations in the compose.yaml and .env file

In the compose.yaml
```   
    #runtime: nvidia
    
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
```
In the .env file
```
# NVIDIA_VISIBLE_DEVICES=all
# NVIDIA_DRIVER_CAPABILITIES=all
```

I found the sources for this flags at https://forums.developer.nvidia.com/t/nvidia-docker-runtime-does-not-seem-to-work-with-docker-compose/307879/2.


To test the configurations I just uncommented what I wanted.

And inside the container ran the following commands:

- nvidia-smi
    - Error 1: bash: nvidia-smi: command not found 
        - Where it appears:  running the command in the terminal
- gz sim -v 4
    - Error 2: failed to create drawable.
        - Where it appears: screen where you can choose the simulations, also appears after choosing simulation

    - Error 3: libEGL warning: egl: failed to create dri2 screen

        MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
        - Where it appears: after choosing a simulation

The simulation only worked properly if error 3 did not occur.

❌/❌/❌ means: You had Error 1/ Had Error 2 / Had Error 3

✅/❌/❌ means: You did not have Error 1/ Had Error 2 / Had Error 3

This is the result

| .env\compose.yaml                               | None | runtime | deploy | 
|--------------------------------------|---------|--------|--------|
| None                                 |    ❌/❌/❌   |    ❌/❌/❌   |   ✅/❌/❌   |
| NVIDIA_VISIBLE_DEVICES=all           |    ❌/❌/❌   |    ✅/❌/❌   |   ✅/❌/❌  |
| NVIDIA_DRIVER_CAPABILITIES=all       |    ❌/❌/❌   |    ❌/❌/❌   |   ✅/✅/❌   |
| Both                                 |    ❌/❌/❌   |    ✅/✅/✅   |   ✅/✅/❌   |


As you can see, the only configuration that worked was runtime with both flags set.
However, using runtime, nvidia-smi cannot detect which process is using the gpu. Whereas, with deploy you can, but gazebo did not work with deploy configuration. I do not need it to work with deploy, but I thought it is important to know that a problem may still exist.

<img width="759" height="351" alt="Image" src="https://github.com/user-attachments/assets/652da533-a0ad-4eb2-949e-6deb6c5085af" />

**Comment by mini-1235** [comment]
> [@mini-1235](https://github.com/mini-1235) you probably just need to append `--runtime=nvidia`.
> 
> If this solves the issue for you then let me know.

Also works for me, thanks!

Feel free to close the issue

**Comment by arilow** [comment]
Thank you @MDEAGEWT!
